version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: ARM
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
skip_commits:
  files:
    - docs/
    - '**/*.md'
    - '*.txt'
    - appveyor.yml
    - LICENSE.txt
    - '.gitignor'
before_build:
- cmd: nuget restore
build:
  project: Rca.OneWireLib/Rca.OneWireLib.csproj
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: tkaSnT6XFm7Dq8IJoPVK1qoKjbbIlFfPTk+MBYEZanPhb50nqRMAEL6ucqbKZZfF